export const CORS = process.env.CORS_ORIGIN || 'http://localhost:3000'
export const PORT = process.env.PORT || 3000
export const HOST = process.env.HOST || 'localhost'
export const DATABASE = process.env.POSTGRES_DATABASE
export const USERNAME = process.env.POSTGRES_USERNAME
export const PASSWORD = process.env.POSTGRES_PASSWORD
export const POSTGRES_HOST = process.env.POSTGRES_HOST
export const POSTGRES_PORT = process.env.POSTGRES_PORT
export const JWT_SECRET = process.env.JWT_SECRET
